In [1]:
import numpy as np

In [5]:
grid = np.arange(1,10).reshape((3,3))

In [6]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
x = np.array([1,2,3])

In [10]:
x.reshape((1,3))

array([[1, 2, 3]])

In [11]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [12]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [13]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [14]:
x = np.array([1,2,3])

In [15]:
y = np.array([3,2,1])

In [16]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [17]:
z=[99,99,99]

In [19]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [20]:
grid = np.array([[1,2,3],[4,5,6]])

In [23]:
np.concatenate([grid , grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [25]:
np.concatenate([grid , grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [26]:
x = np.array([1,2,3])

In [28]:
grid = np.array([[9,8,7],[6,5,4]])

In [29]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [30]:
y = np.array([[99],[99]])

In [32]:
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [33]:
x = [1,2,3,99,99,3,2,1]

In [34]:
x1, x2, x3 = np.split(x,[3,5])

In [35]:
x1

array([1, 2, 3])

In [36]:
x2

array([99, 99])

In [37]:
x3

array([3, 2, 1])

In [38]:
grid = np.arange(16).reshape(4,4)

In [39]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
upper ,lower = np.vsplit(grid ,[2])

In [41]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [42]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
left, right = np.hsplit(grid ,[2])

In [44]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [45]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [46]:
x = np.arange(4)

In [47]:
x

array([0, 1, 2, 3])

In [48]:
x+5

array([5, 6, 7, 8])

In [49]:
x-5

array([-5, -4, -3, -2])

In [50]:
x*2

array([0, 2, 4, 6])

In [51]:
x/2

array([0. , 0.5, 1. , 1.5])

In [52]:
x//2

array([0, 0, 1, 1], dtype=int32)

In [53]:
x**2

array([0, 1, 4, 9])

In [54]:
x%2

array([0, 1, 0, 1], dtype=int32)

In [55]:
np.add(x,2)

array([2, 3, 4, 5])

In [56]:
np.subtract(x,2)

array([-2, -1,  0,  1])

In [57]:
np.multiply(x,3)

array([0, 3, 6, 9])

In [58]:
np.negative(x)

array([ 0, -1, -2, -3])

In [59]:
np.divide(x,2)

array([0. , 0.5, 1. , 1.5])

In [60]:
np.floor_divide(x,2)

array([0, 0, 1, 1], dtype=int32)

In [61]:
np.power(x,2)

array([0, 1, 4, 9], dtype=int32)

In [62]:
np.mod(x,2)

array([0, 1, 0, 1], dtype=int32)

In [63]:
x = np.array([-2,-1,0,1,2])

In [64]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [65]:
theta = np.linspace(0,np.pi,3)

In [66]:
theta

array([0.        , 1.57079633, 3.14159265])

In [67]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [69]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [70]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [71]:
x=[-1,0,1]

In [72]:
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [73]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [74]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

In [78]:
x =[1,2,3]

In [79]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [80]:
np.exp2(x)

array([2., 4., 8.])

In [81]:
np.power(3,x)

array([ 3,  9, 27], dtype=int32)

In [82]:
x = [1,2,3]

In [83]:
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [84]:
np.log2(x)

array([0.       , 1.       , 1.5849625])

In [85]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125])

In [86]:
L = np.random.random(100)

In [87]:
sum(L)

52.398799685396526

In [88]:
np.min(L)

0.024135370738537998

In [89]:
np.max(L)

0.9993435579386963

In [92]:
M =  np.random.random((3,4))

In [93]:
M

array([[0.87655426, 0.08374776, 0.69924335, 0.00106285],
       [0.92825443, 0.3636165 , 0.12598441, 0.55572936],
       [0.0167651 , 0.08485068, 0.20237426, 0.26433333]])

In [94]:
M.min(axis=0
     )

array([0.0167651 , 0.08374776, 0.12598441, 0.00106285])

In [95]:
M.max(axis = 1)

array([0.87655426, 0.92825443, 0.26433333])

In [96]:
height = np.array([189,170,183,170,168,162,182,183,172,175,193])

In [97]:
height.mean()

177.0

In [98]:
height.std()

9.19486022435657

In [99]:
height.min()

162

In [100]:
height.max()

193

In [101]:
np.percentile(height,25)

170.0

In [102]:
np.median(height)

175.0

In [103]:
np.percentile(height, 75)

183.0

In [104]:
a = np.array([0,1,2])

In [105]:
M = np.ones((3,3))

In [106]:
x = M+a

In [107]:
x

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [108]:
a = np.arange(3)

In [110]:
b = np.arange(3)[:,np.newaxis]

In [111]:
a

array([0, 1, 2])

In [112]:
b

array([[0],
       [1],
       [2]])

In [113]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [114]:
x<3

array([[ True,  True, False],
       [ True,  True, False],
       [ True,  True, False]])

In [116]:
x>3

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [117]:
x<=3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [118]:
x>=3

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [119]:
x!=3

array([[ True,  True, False],
       [ True,  True, False],
       [ True,  True, False]])

In [120]:
x==3

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [121]:
x = np.random.randint(10, size=(3,4))

In [122]:
x<6

array([[False,  True,  True, False],
       [False,  True,  True,  True],
       [ True,  True, False,  True]])

In [123]:
np.count_nonzero(x<6)

8

In [124]:
np.sum(x<6)

8

In [126]:
np.sum(x<6, axis= 1)

array([2, 3, 3])

In [127]:
np.any(x>8)

True

In [128]:
np.any(x<0)

False

In [129]:
np.all(x<10)

True

In [130]:
np.all(x<8,axis=1)

array([False,  True, False])

In [131]:
x[x<5]

array([4, 4, 1, 2])

In [132]:
bool(42)

True

In [133]:
bool(0)

False

In [134]:
bool(42 and 0)

False

In [136]:
bool(42 or 0)

True

In [137]:
x = np.arange(10)

In [138]:
(x>4)& (x<8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [139]:
x = np.array([2,1,4,3,5])

In [140]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [141]:
i = np.argsort(x)

In [142]:
i

array([1, 0, 3, 2, 4], dtype=int64)

In [144]:
x = np.random.randint(0,10,(4,6))

In [145]:
x

array([[6, 3, 2, 6, 5, 5],
       [6, 3, 9, 7, 2, 1],
       [3, 4, 9, 5, 3, 7],
       [0, 3, 3, 1, 4, 9]])

In [146]:
np.sort(x, axis=0)

array([[0, 3, 2, 1, 2, 1],
       [3, 3, 3, 5, 3, 5],
       [6, 3, 9, 6, 4, 7],
       [6, 4, 9, 7, 5, 9]])

In [147]:
np.sort(x,axis=1)

array([[2, 3, 5, 5, 6, 6],
       [1, 2, 3, 6, 7, 9],
       [3, 3, 4, 5, 7, 9],
       [0, 1, 3, 3, 4, 9]])

In [148]:
x = np.array([7,2,3,1,6,5,4])

In [149]:
np.partition(x,3)

array([2, 1, 3, 4, 6, 5, 7])

In [150]:
name=['alice','bob','cathy','doug']

In [151]:
age=[25,45,37,19]

In [152]:
weight = [55.0, 85.5 ,63.0 ,61.5]

In [159]:
data = np.zeros(4, dtype ={'names' :('name','Age','weight'),'format':('UIO','14','f8')})

ValueError: invalid literal for int() with base 10: 'Age'