In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
data = pd.Series([0.25,0.5,0.75,1.0])

In [5]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [6]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [7]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
data[1]

0.5

In [9]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [10]:
data = pd.Series([0.25, 0.5 , 0.75 ,1.0], index =['a','b','c','d'])

In [11]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [12]:
data['b']

0.5

In [13]:
data = pd.Series([0.25,0.5,0.75 ,1.0],index=[2,5,3,7])

In [14]:
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [15]:
data[5]

0.5

In [16]:
population_dict ={'california': 38332521,
                   'Texas':26448193,
                  'Newyork': 19651127,
                  'florida': 19552860,
                  'Illinais':12882135
                 }

In [17]:
population = pd.Series(population_dict)

In [18]:
population

california    38332521
Texas         26448193
Newyork       19651127
florida       19552860
Illinais      12882135
dtype: int64

In [19]:
x = pd.DataFrame (population, columns=['population'])

In [20]:
x

population
california    38332521
Texas         26448193
Newyork       19651127
florida       19552860
Illinais      12882135

In [21]:
data = [{'a':i , b'':2*i} for i in range(3)]

In [22]:
data

[{'a': 0, b'': 0}, {'a': 1, b'': 2}, {'a': 2, b'': 4}]

In [23]:
x2 = pd.DataFrame(data)

In [24]:
x2

a  b''
0  0    0
1  1    2
2  2    4

In [25]:
x3 = pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

In [26]:
x3

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [27]:
area_dict = {'california': 38332521,
                   'Texas':26448193,
                  'Newyork': 19651127,
                  'florida': 19552860,
                  'Illinais':12882135
                 }

In [28]:
area = pd.Series(area_dict)

In [29]:
x4 = pd.DataFrame({'population':population,'area':area})

In [30]:
x4

population      area
california    38332521  38332521
Texas         26448193  26448193
Newyork       19651127  19651127
florida       19552860  19552860
Illinais      12882135  12882135

In [31]:
x5 = pd.DataFrame(np.random.rand(3,2), columns=['foo','bar'], index =['a','b','c'])

In [32]:
x5

foo       bar
a  0.474630  0.976798
b  0.006989  0.331404
c  0.580542  0.080015

In [33]:
a = np.zeros(3, dtype=[('A','i8'),('B','f8')])

In [34]:
a

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [35]:
x6 = pd.DataFrame(a)

In [36]:
x6

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [37]:
data = pd.Series([0.25,0.5,0.75,1.0], index=['a','b','c','d'])

In [38]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [39]:
data['b']

0.5

In [41]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [42]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [44]:
data['e'] = 1.25

In [45]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [46]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [47]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [48]:
data[(data>0.3) & (data<0.8)]

b    0.50
c    0.75
dtype: float64

In [49]:
data[('a','e')]

KeyError: 'key of type tuple not found and not a MultiIndex'

In [50]:
data = pd.Series(['a','b','c'], index=[1,2,5])

In [51]:
data

1    a
2    b
5    c
dtype: object

In [52]:
data[1:3]

C:\Users\New\AppData\Local\Temp\ipykernel_4288\797807744.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  data[1:3]


2    b
5    c
dtype: object

In [53]:
data.loc[1]

'a'

In [55]:
data.loc[1:3]

1    a
2    b
dtype: object

In [58]:
data.iloc[1]

'b'

In [59]:
data.iloc[1:3]

2    b
5    c
dtype: object

In [61]:
data = pd.DataFrame({'area':area, 'population':population})

In [62]:
data['area']

california    38332521
Texas         26448193
Newyork       19651127
florida       19552860
Illinais      12882135
Name: area, dtype: int64

In [63]:
data.area


california    38332521
Texas         26448193
Newyork       19651127
florida       19552860
Illinais      12882135
Name: area, dtype: int64

In [64]:
data['density']= data['population']/data['area']

In [65]:
data

area  population  density
california  38332521    38332521      1.0
Texas       26448193    26448193      1.0
Newyork     19651127    19651127      1.0
florida     19552860    19552860      1.0
Illinais    12882135    12882135      1.0

In [66]:
data.values

array([[3.8332521e+07, 3.8332521e+07, 1.0000000e+00],
       [2.6448193e+07, 2.6448193e+07, 1.0000000e+00],
       [1.9651127e+07, 1.9651127e+07, 1.0000000e+00],
       [1.9552860e+07, 1.9552860e+07, 1.0000000e+00],
       [1.2882135e+07, 1.2882135e+07, 1.0000000e+00]])

In [67]:
data.T

california       Texas     Newyork     florida    Illinais
area        38332521.0  26448193.0  19651127.0  19552860.0  12882135.0
population  38332521.0  26448193.0  19651127.0  19552860.0  12882135.0
density            1.0         1.0         1.0         1.0         1.0

In [69]:
data.values[0]

array([3.8332521e+07, 3.8332521e+07, 1.0000000e+00])

In [70]:
data.iloc[:3,:2]

area  population
california  38332521    38332521
Texas       26448193    26448193
Newyork     19651127    19651127

In [74]:
data.iloc[:'Illiones',:'population']

TypeError: cannot do positional indexing on Index with these indexers [Illiones] of type str

In [75]:
data.ix[:3,:'population']

AttributeError: 'DataFrame' object has no attribute 'ix'

In [78]:
data.loc[data.density>100 ,['population','density']]

Empty DataFrame
Columns: [population, density]
Index: []

In [80]:
data.iloc[0,2] = 90

In [81]:
rng = np.random.RandomState(42)

In [83]:
ser = pd.Series(rng.randint(0,10,4))

In [84]:
ser

0    6
1    3
2    7
3    4
dtype: int32

In [85]:
df = pd.DataFrame(rng.randint(0,10,(3,4)))

In [86]:
df

0  1  2  3
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [87]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [88]:
np.sin(df*np.pi/4)

0             1         2             3
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [89]:
a = pd.Series([2,4,6],index=[0,1,2])

In [90]:
b = pd.Series([1,3,5],index=[1,2,3])

In [91]:
a +b

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [93]:
x = a.add(b, fill_value =0)

In [94]:
x

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [95]:
a = pd.DataFrame(rng.randint(0,10,(2,3)))

In [97]:
b = pd.DataFrame(rng.randint(0,10,(3,3)),columns=list('BAC'))

In [98]:
b

B  A  C
0  2  4  2
1  6  4  8
2  6  1  3

In [99]:
a+b

0   1   2   A   B   C
0 NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN

In [101]:
a.add(b , fill_value_full)

NameError: name 'fill_value_full' is not defined

In [102]:
data = pd.Series([1,np.NAN,'hello','Nan'])

In [103]:
data

0        1
1      NaN
2    hello
3      Nan
dtype: object

In [105]:
data.isnull()

0    False
1     True
2    False
3    False
dtype: bool

In [106]:
data.isnull()

0    False
1     True
2    False
3    False
dtype: bool

In [107]:
data.notnull()

0     True
1    False
2     True
3     True
dtype: bool

In [108]:
data.dropna()

0        1
2    hello
3      Nan
dtype: object

In [110]:
df = pd.DataFrame([[1,np.NAN,2],
                 [2,3,4],
                  [np.nan,4,6]
                  ]
                 )

In [111]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  4
2  NaN  4.0  6

In [113]:
df.dropna()

0    1  2
1  2.0  3.0  4

In [114]:
df.dropna(axis = 'columns')

2
0  2
1  4
2  6

In [118]:
df[3]=np.nan

In [119]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  4 NaN
2  NaN  4.0  6 NaN

In [120]:
df.dropna(axis ='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  4
2  NaN  4.0  6

In [124]:

df.dropna(axis='rows',thresh =3)

0    1  2   3
1  2.0  3.0  4 NaN

In [126]:
data = pd.Series ([1,np.nan,2 ,None,3 ], index =list('abcde'))

In [127]:
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [129]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [130]:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [133]:
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [132]:
df.fillna(method="ffill",axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  4.0  4.0
2  NaN  4.0  6.0  6.0