In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pandas as pd

In [49]:
model = LogisticRegression()
model2 = LinearRegression()


In [50]:
df = pd.read_csv('pima-indians-diabetes.csv')

In [51]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Class  
0                       0.627   50      1  
1                       0.351   31      0  
2                       0.672   32      1  
3                       0.167   21      0  
4                       2.288   33      1  
..                        ...  ...    ...  
763                     0.171   63      0  
764                     0.340   27      0  
765                     0.245   30      0  
766                     0.349   47      1  
767                     0.315   23      0  

[768 rows x 9 columns]

In [52]:
xtrain,xtest,ytrain,ytest = train_test_split(
    df[['Age','Pregnancies','BloodPressure','BMI','Glucose']],
    df.Class,
    test_size=0.3,   
)

In [53]:
xtrain

Age  Pregnancies  BloodPressure   BMI  Glucose
54    42            7             66  34.7      150
134   26            2             68  21.1       96
440   41            0            104  34.3      189
633   22            1             82  27.5      128
449   26            0             74  30.5      120
..   ...          ...            ...   ...      ...
727   22            0             84  32.4      141
363   67            4             78  38.5      146
47    22            2             70  28.0       71
42    48            7             92  22.7      106
566   21            1             72  38.6       99

[537 rows x 5 columns]

In [54]:
ytrain

54     0
134    0
440    1
633    0
449    0
      ..
727    0
363    1
47     0
42     0
566    0
Name: Class, Length: 537, dtype: int64

In [55]:
model.fit(xtrain,ytrain)

TypeError: LogisticRegression.fit() missing 1 required positional argument: 'y'

In [56]:
model.score(xtest,ytest)

TypeError: ClassifierMixin.score() missing 1 required positional argument: 'y'

In [24]:
x = model.predict(xtest)

In [31]:
model.predict([[67,0,200,110.0,140]])

C:\Users\CSELAB1SYS10\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [34]:
xtrain,xtest,ytrain,ytest = train_test_split(
    df[['Pregnancies','BloodPressure','BMI','Glucose','Class']],
    df.Age,
    test_size=0.3,   
)

In [35]:
xtrain

Pregnancies  BloodPressure   BMI  Glucose  Class
75             1             48  24.7        0      0
670            6             68  33.6      165      0
424            8             78  42.9      151      1
595            0             82  32.0      188      1
124            0             76  33.3      113      1
..           ...            ...   ...      ...    ...
223            7             60  28.8      142      0
72            13             90  43.4      126      1
298           14             78  36.6      100      1
546            5             76  43.6      187      1
32             3             58  24.8       88      0

[537 rows x 5 columns]

In [36]:
ytrain

75     22
670    49
424    36
595    22
124    23
       ..
223    61
72     42
298    46
546    53
32     22
Name: Age, Length: 537, dtype: int64

In [38]:
model2.fit(xtrain,ytrain)

TypeError: LinearRegression.fit() missing 1 required positional argument: 'y'

In [39]:
model2.fit??

In [43]:
dataset = pd.read_csv("dia.csv")
model3 = LinearRegression()

In [44]:
x = dataset.iloc[:,:-1].values

In [45]:
y = dataset.iloc[:,:-1].values

In [56]:
result = model3.fit(x,y)

In [61]:
model3.predict(x[[0]])

array([[ 6.00000000e+00,  1.48000000e+02,  7.20000000e+01,
         3.50000000e+01, -6.01756525e-14,  3.36000000e+01,
         6.27000000e-01,  5.00000000e+01]])

In [48]:
model3

AttributeError: 'LinearRegression' object has no attribute 'summary'

In [4]:
pip install statsmodels

     ---------------------------------------- 9.1/9.1 MB 1.4 MB/s eta 0:00:00
     ------------------------------------ 233.8/233.8 kB 955.5 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [27]:
import pandas as pd 
import statsmodels.api as sm
import numpy as np

In [28]:
dataset = pd.read_csv("dia.csv")

In [29]:
x = dataset.iloc[:,:-1].values

In [69]:
y = dataset.iloc[:,:-1].values

In [70]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [71]:
y = dataset.loc[:,"Outcome"].values

In [72]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [73]:
model = sm.OLS(y,x)

In [74]:
result = model.fit()

In [75]:
model.predict(x[0])

array([31978.353129, 20796.980077, 34123.301344, 20729.264709,
       27480.594576, 24886.286027, 18623.755496, 19716.164018,
       39457.899066, 28160.145464, 25691.479757, 33229.136699,
       30153.463507, 37064.609546, 33864.248049, 17450.303468,
       28246.225477, 23750.719258, 21844.994741, 25878.891683,
       29107.921408, 24437.683276, 38917.562777, 27075.564901,
       32932.919258, 27605.088535, 30744.001139, 21518.825349,
       31703.073615, 27015.971299, 26681.942342, 32596.293577,
       19536.447409, 22344.757876, 27994.681024, 23200.005682,
       28827.78334 , 25322.856955, 22331.835381, 27328.43153 ,
       34583.569917, 28975.156392, 26146.867345, 38347.892067,
       31102.824338, 35419.386911, 28094.273628, 18546.167422,
       24021.975688, 16782.191235, 23147.147857, 21192.449802,
       20861.054434, 37798.612809, 31730.370186, 16582.955496,
       37295.879258, 26359.083174, 31073.916687, 24077.508471,
       13494.190608, 27971.60929 , 13646.368049, 28299.

In [77]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.487
Model:                            OLS   Adj. R-squared (uncentered):              0.481
Method:                 Least Squares   F-statistic:                              90.10
Date:                Wed, 14 Dec 2022   Prob (F-statistic):                   9.04e-105
Time:                        14:49:43   Log-Likelihood:                         -429.34
No. Observations:                 768   AIC:                                      874.7
Df Residuals:                     760   BIC:                                      911.8
Df Model:                           8                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0247      0.005      4.536      0.000       0.014       0.035
x2             0.0039      0.001      7.701      0.000       0.003       0.005
x3            -0.0049      0.001     -6.005      0.000      -0.007      -0.003
x4          5.752e-05      0.001      0.049      0.961      -0.002       0.002
x5          4.783e-05      0.000      0.304      0.761      -0.000       0.000
x6             0.0042      0.002      2.094      0.037       0.000       0.008
x7             0.0980      0.048      2.059      0.040       0.005       0.191
x8            -0.0010      0.002     -0.652      0.515      -0.004       0.002
==============================================================================
Omnibus:                      294.015   Durbin-Watson:                   2.034
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               80.012
Skew:                           0.574   Prob(JB):                     4.22e-18
Kurtosis:                       1.913   Cond. No.                         575.
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""